@include('woo-commerce::admin.general.header')
@include('woo-commerce::admin.general.navbar')
@include('woo-commerce::admin.general.nav-sidebar')
@yield('content')
@include('woo-commerce::admin.general.footer')